### ISSUE TITLE
Changing TCPIPs will not increase bandwidth.

### ISSUE THREAD

**Issue by NotAspects** [auraside/HoneCtrl#17]
Changing the values of the "TCPIP" register will not increase your bandwidth in any way, on the contrary it may reduce your connection. 

![image](https://user-images.githubusercontent.com/73410229/182023204-e537c3c7-0ea0-4bc4-9dfd-408f6a7cdf17.png)
![image](https://user-images.githubusercontent.com/73410229/182023459-36fec3bf-5e50-4114-8cf3-27b6a50cf6b3.png)

Before : 
![image](https://user-images.githubusercontent.com/73410229/182023419-e19ff3d3-ffc8-4dbe-b811-3dedc0af2136.png)

After : 
![image](https://user-images.githubusercontent.com/73410229/182023426-0158a72e-3e43-4b18-82ef-3e6700d8e585.png)

**Comment by Vojtazz** [comment]
do agree

**Comment by rn9551** [comment]
The title of this issue is correct:
There's not a single internet tweak that can increase your bandwidth, or reduce ping. From what I see, none of our descriptions have said that we increase your bandwidth.

The goal of the TCPIP optimizations is to modify the driver for smoother gameplay in TCP-related games. People have been applying similar optimizations to make their windows servers more efficient, this has been a practice that has been occurring since the 90's if not earlier. 

These improvements are also not measurable via a speedtest, your connection should stay the same. 

This next update should (hopefully) fix any outstanding internet issues, since we did see a few things that could potentially lower speeds, feel free to make another issue if you see anything wrong.
