### ISSUE TITLE
Page 1 Won't Open

### ISSUE THREAD

**Issue by D4rkPho3n1x1** [auraside/HoneCtrl#53]
Not sure if this is just me but whenever I download the batch file and run it as admin and I press 1 to go into the main optimizations, Windows PowerShell just goes blank for a second and then disappears.

Same thing when trying to use terminal but instead it just opens up a new blank tab

**Comment by D4rkPho3n1x1** [comment]
Update:

I tried using the newest version on my Acer Nitro 5 laptop and it worked just fine (AN515-51 model) so it seems to just be something with my desktop, I'll provide specs below in case it helps.

I also tried sharing that exact version of the program with my desktop through Google Drive with no dice. Hone is in my C drive on both systems so drive location isn't an issue either.

CPU: AMD Ryzen 5 2600
MB: MSI B550 A-Pro
RAM: 2x8gb Corsair Vengeance LPX @ 3200mhz
GPU: MSI RTX 3060 Ventus 2x OC
OS: Windows 11 Home

If other specs are needed just let me know, It's a DIY build so I should know them. Also running on WiFi because my house doesn't have ethernet ports.

**Comment by Scarlaid** [comment]
You aren't alone, Page 1 and 6 are not open for me since then, the rest works fine I presume

**Comment by Guanran928** [comment]
Line 292, `wmic path Win32_Battery Get BatteryStatus | find "1" && set "PWROF=%COL%[93mN/A"`

The culprit is WMIC is missing from your system.
If you are on Windows 11. Go to Settings -> Apps -> Optional Features, click on `Add an optional feature` and install WMIC.

(my system is bugged and i somehow cant reinstall wmic, fuck you microsoft)
![image](https://github.com/auraside/HoneCtrl/assets/68757440/ad22948c-e335-490f-99ca-3d6ab23b1164)
